version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
  my-nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 9091:90