apiVersion: v1
kind: Pod
metadata:
  name: nginx-service-pod
spec:
  containers:
    - name: nginx-container
      image: ngnix-demo_my-nginx:latest
      ports:
        - 9091:90
    - name: webapp-service-container
        image: ngnix-demo_webapp:latest
        ports:
          - 8081:8081